name: RestartAR
version: '${project.version}'
main: me.marioneto4ka.restartar.RestartAR
api-version: 1.17
commands:
  ar:
    usage: /ar <restart [time]|cancel|reload|help>
    permission: restartar.admin
permissions:
  restartar.admin:
    default: op
