name: RestartAR
version: '1.9.0'
main: me.marioneto4ka.restartar.RestartAR
api-version: '1.21'
commands:
  ar:
    usage: /ar <restart [time]|cancel|reload|help>
    permission: restartar.admin
permissions:
  restartar.admin:
    default: op
